// E2E con API real del servidor tests/preview_app.py; no usa la BD del usuario.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const base=process.env.PRACTICE_PREVIEW_URL || 'http://127.0.0.1:8766';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:390,height:844}}), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{
   Object.defineProperty(crypto,'randomUUID',{value:undefined});
   localStorage.setItem('duofeynman_token','preview');
   localStorage.setItem('duofeynman_user',JSON.stringify({id:1,username:'Preview',current_level:'A1'}));
  });
  await page.goto(base);
  await page.locator('#view-home.active').waitFor();
  await page.locator('#btn-daily').click();
  await page.locator('.daily-start').first().waitFor();
  assert((await page.locator('#daily-content').textContent()).includes('This correction is due'));
  await page.locator('.daily-start').first().click();
  await page.locator('#drill-answer').fill('I am tired');
  await page.locator('#drill-form button[type="submit"]').click();
  await page.locator('#drill-feedback').getByText('Correct!',{exact:true}).waitFor();
  await page.locator('#view-srs .btn-back-home').click();
  await page.locator('#btn-daily').click();
  await page.locator('.daily-item.done').waitFor();
  await page.locator('#view-daily .btn-back-home').click();
  await page.locator('.quick-btn[data-action="listening"]').click();
  await page.locator('#listening-play').waitFor();
  assert.equal((await page.locator('#listening-text').textContent()).trim(),'');
  await page.locator('#listening-play').click();
  await page.waitForFunction(()=>!document.getElementById('listening-check').disabled);
  await page.locator('input[name="meaning"]').first().check();
  await page.locator('#listening-check').click();
  await page.locator('#listening-feedback').getByText('Listening result saved.',{exact:true}).waitFor();
  assert((await page.locator('#listening-text').textContent()).length > 20);
  await page.locator('#listening-next').click();
  await page.locator('#listening-reveal').click();
  await page.locator('input[name="meaning"]').first().check();
  await page.locator('#listening-check').click();
  await page.locator('#listening-feedback').getByText('Saved as guided practice.',{exact:true}).waitFor();
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:path.join(require('node:os').tmpdir(),'duofeynman-listening.png'),animations:'disabled'});
  await page.locator('#view-listening .btn-back-home').click();
  await page.locator('.quick-btn[data-action="dialogues"]').click();
  await page.locator('.dlg-start').first().click();
  await page.locator('#choose-options .choose-option').first().waitFor();
  await page.locator('#choose-options .choose-option').first().click();
  const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/dialogues/turn/check'));
  await page.locator('#btn-choose-send').click();
  const response=await (await responsePromise).json();
  assert.equal(response.session.responses.length,1);
  // Recargar pierde memoria JS: volver debe reconstruir la respuesta guardada.
  await page.reload();
  await page.locator('#view-home.active').waitFor();
  await page.locator('.quick-btn[data-action="dialogues"]').click();
  await page.locator('.dlg-start').first().click();
  await page.locator('#chat-messages .chat-msg.user').waitFor();
  assert((await page.locator('#chat-messages .chat-msg.user').first().textContent()).includes(response.session.responses[0].text));
  await page.locator('.input-mode-btn[data-input-mode="type"],.input-mode-btn[data-mode="type"]').first().click();
  await page.locator('#chat-input').fill('no sé qué decir');
  await page.locator('#btn-chat-send').click();
  await page.locator('.fb-continue').waitFor();
  await page.reload();
  await page.locator('#view-home.active').waitFor();
  await page.locator('.quick-btn[data-action="dialogues"]').click();
  await page.locator('.dlg-start').first().click();
  await page.locator('.fb-continue').waitFor();
  await page.locator('.fb-continue').click();
  await page.waitForTimeout(1500);
  assert.equal(await page.locator('.view.active').getAttribute('id'),'view-chat');
  const width=await page.evaluate(()=>({content:document.documentElement.scrollWidth,screen:innerWidth}));
  assert(width.content<=width.screen+2,JSON.stringify(width));
  assert.deepEqual(errors,[]);
  await page.locator('#view-chat .btn-back-dialogues').first().click();
  await page.locator('#view-dialogues .btn-back-home').click();
  await page.locator('#btn-daily').click();
  await page.locator('.daily-start').first().waitFor();
  await page.locator('#view-daily .theme-toggle').click();
  await page.screenshot({path:path.join(require('node:os').tmpdir(),'duofeynman-daily-dark.png'),animations:'disabled'});
  await page.setViewportSize({width:1280,height:900});
  const desktop=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2);
  assert(desktop);
  console.log('PRACTICE_E2E_OK: daily plan, drill, listening, guided mode, dialogue reload, failed-turn resume, continue, mobile');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
